const lista_filmes = [
//    '120 Dias de Sodoma.mp4','120 Dias de Sodoma.jpg', 
'https://archive.org/download/60-minutos-para-morrer-2017/60 Minutos Para Morrer - 2017.mp4','60 Minutos Para Morrer - 2017.jpg', 
//'7 Desejos - 2017.mkv','7 Desejos - 2017.jpg', 
'https://archive.org/download/o-silencio-dos-inocentes/O Silencio dos Inocentes.mp4','O Silencio dos Inocentes.jpg',
'https://archive.org/download/a-arte-do-demonio-2004/A Arte do Demonio - 2004.mp4','A Arte do Demonio - 2004.jpg', 
'https://archive.org/download/a-arte-do-demonio-2-2005/A Arte do Demonio 2 - 2005.mp4','A Arte do Demonio 2 - 2005.jpg', 
'https://archive.org/download/a-arte-do-demonio-3-2008/A Arte do Demonio 3 - 2008.mp4','A Arte do Demonio 3 - 2008.jpg', 
'https://archive.org/download/a-autopsia/A Autopsia.ia.mp4','A Autopsia.jpg', 
'https://archive.org/download/a-bolha-assasina-1958/A Bolha Assasina 1958.mp4','A Bolha Assasina 1958.jpg', 
'https://archive.org/download/a-bolha-assassina-1988_202507/A Bolha Assassina - 1988.mp4','A Bolha Assassina - 1988.jpg', 
'https://archive.org/download/a-casa-amaldicoada-1999/A Casa Amaldiçoada - 1999.mp4','A Casa Amaldiçoada - 1999.jpg', 
'https://archive.org/download/a-casa-dos-1000-corpos_202507/A Casa Dos 1000 Corpos.mp4','A Casa Dos 1000 Corpos.jpg', 
'https://archive.org/download/a-casa-que-jack-construiu/A Casa Que Jack Construiu.ia.mp4','A Casa Que Jack Construiu.jpg', 
//------------------------------'https://archive.org/download/a-casa-da-colina-1999/A Casa da Colina - 1999.mp4','A Casa da Colina - 1999.jpg', 
'https://archive.org/download/a-casa-de-vidro-1-2001/A Casa de Vidro 1 - 2001.mp4','A Casa de Vidro 1 - 2001.jpg', 
'https://archive.org/download/a-casa-de-vidro-2-2006/A Casa de Vidro 2 - 2006.mp4','A Casa de Vidro 2 - 2006.jpg', 
'https://archive.org/download/a-casa-do-espanto-1/A Casa do Espanto 1.mp4','A Casa do Espanto 1.jpg', 
'https://archive.org/download/a-casa-do-espanto-2_202507/A Casa do Espanto 2.mp4','A Casa do Espanto 2.jpg', 
'https://archive.org/download/a-casa-do-espanto-3_202507/A Casa do Espanto 3.mp4','A Casa do Espanto 3.jpg', 
'https://archive.org/download/a-casa-do-espanto-4_202507/A Casa do Espanto 4.mp4','A Casa do Espanto 4.jpg', 
'https://archive.org/download/a-casa-dos-mortos-o-filme-2003/A Casa dos Mortos  - O Filme - 2003.mp4','A Casa dos Mortos  - O Filme - 2003.jpg', 
'https://archive.org/download/a-casa-dos-mortos-2-2005/A Casa dos Mortos 2 - 2005.mp4','A Casa dos Mortos 2 - 2005.jpg', 
'https://archive.org/download/a-casa-dos-passaros-mortos/A Casa dos Passaros Mortos.mp4','A Casa dos Passaros Mortos.jpg', 
'https://archive.org/download/a-casa-que-pingava-sangue-1971_202507/A Casa que Pingava Sangue - 1971.mp4','A Casa que Pingava Sangue - 1971.jpg', 
'https://archive.org/download/a-caverna-2005/A Caverna - 2005.mp4','A Caverna - 2005.jpg', 
'https://archive.org/download/a-caverna-maldita-2006/A Caverna Maldita - 2006.mp4','A Caverna Maldita - 2006.jpg', 
'https://archive.org/download/a-coisa-2011/A Coisa - 2011.mp4','A Coisa - 2011.jpg', 
'https://archive.org/download/a-enfermeira-assassina-2014/A Enfermeira Assassina - 2014.mp4','A Enfermeira Assassina - 2014.jpg', 
'https://archive.org/download/a-entidade-2/A Entidade 2.ia.mp4','A Entidade 2.jpg', 
'https://archive.org/download/a-entidade_202507/A Entidade.ia.mp4','A Entidade.jpg', 
'https://archive.org/download/a-epidemia-2010/A Epidemia - 2010.mp4','A Epidemia - 2010.jpg', 
'https://archive.org/download/a-espera-do-mal-2005/A Espera do Mal - 2005.mp4','A Espera do Mal - 2005.jpg', 
'https://archive.org/download/a-experiencia-1995/A Experiência - 1995.mp4','A Experiência - 1995.jpg', 
'https://archive.org/download/a-experiencia-2-1998_20250708/A Experiência 2 - 1998.mp4','A Experiência 2 - 1998.jpg', 
'https://archive.org/download/a-experiencia-3-2004_202507/A Experiência 3 - 2004.mp4','A Experiência 3 - 2004.jpg', 
'https://archive.org/download/a-experiencia-4-o-despertar-2007_202507/A Experiência 4 - O Despertar - 2007.mp4','A Experiência 4 - O Despertar - 2007.jpg', 
'https://archive.org/download/a-filha-de-dracula-1936/A Filha de Drácula - 1936.mp4','A Filha de Drácula - 1936.jpg', 
'https://archive.org/download/a-forca-2015/A Forca - 2015.mp4','A Forca - 2015.jpg', 
'https://archive.org/download/a-freira-2/A Freira 2.mp4','A Freira 2.jpg', 
'https://archive.org/download/a-freira_202507/A Freira.ia.mp4','A Freira.jpg', 
'https://archive.org/download/a-fronteira_202507/A Fronteira.mp4','A Fronteira.jpg', 
'https://archive.org/download/a-gruta-2020_202507/A Gruta - 2020.mp4','A Gruta - 2020.jpg', 
'https://archive.org/download/a-hora-do-espanto-2/A Hora do Espanto 2.mp4','A Hora do Espanto 2.jpg', 
'https://archive.org/download/a-hora-do-espanto-3/A Hora do Espanto 3.ia.mp4','A Hora do Espanto 3.jpg', 
'https://archive.org/download/a-hora-do-espanto_202507/A Hora do Espanto.mp4','A Hora do Espanto.jpg', 
'https://archive.org/download/a-hora-do-pesadelo-1_202507/A Hora do Pesadelo 1.mp4','A Hora do Pesadelo 1.jpg', 
'https://archive.org/download/a-hora-do-pesadelo-2/A Hora do Pesadelo 2.mp4','A Hora do Pesadelo 2.jpg', 
'https://archive.org/download/a-hora-do-pesadelo-3/A Hora do Pesadelo 3.mp4','A Hora do Pesadelo 3.jpg', 
'https://archive.org/download/a-hora-do-pesadelo-4/A Hora do Pesadelo 4.mp4','A Hora do Pesadelo 4.jpg', 
'https://archive.org/download/a-hora-do-pesadelo-5/A Hora do Pesadelo 5.mp4','A Hora do Pesadelo 5.jpg', 
'https://archive.org/download/a-hora-do-pesadelo-6/A Hora do Pesadelo 6.mp4','A Hora do Pesadelo 6.jpg', 
'https://archive.org/download/a-hora-do-pesadelo-7/A Hora do Pesadelo 7.mp4','A Hora do Pesadelo 7.jpg', 
'https://archive.org/download/a-ilha-do-dr.-moreau-1996/A Ilha do Dr. Moreau - 1996.mp4','A Ilha do Dr. Moreau - 1996.jpg', 
'https://archive.org/download/a-ilha-dos-mortos/A Ilha dos Mortos.mp4','A Ilha dos Mortos.jpg', 
//'A Luz Do Demonio.mkv','A Luz Do Demonio.jpg', 
'https://archive.org/download/a-maldicao-de-samantha/A Maldicao de Samantha.ia.mp4','A Maldicao de Samantha.jpg', 
'https://archive.org/download/a-maldicao-da-casa-winchester-2018/A Maldição da Casa Winchester - 2018.mp4','A Maldição da Casa Winchester - 2018.jpg', 
'https://archive.org/download/a-maldicao-da-mosca-1965/A Maldição da Mosca - 1965.mp4','A Maldição da Mosca - 1965.jpg', 
'https://archive.org/download/a-maldicao-do-mestre-dos-brinquedos-1998/A Maldição do Mestre dos Brinquedos (1998).ia.mp4','A Maldição do Mestre dos Brinquedos (1998).jpg', 
'https://archive.org/download/a-montanha-dos-canibais-1978/A Montanha dos Canibais - 1978.mp4','A Montanha dos Canibais - 1978.jpg', 
//'A Morte Pede Carona.mp4','A Morte Pede Carona.jpg', 
//'A Morte Te Dá Parabéns 1 - 2018.mkv','A Morte Te Dá Parabéns 1 - 2018.jpg', 
//'A Morte Te Dá Parabéns 2.mp4','A Morte Te Dá Parabéns 2.jpg', 
'https://archive.org/download/a-morte-do-demonio/A Morte do Demonio.ia.mp4','A Morte do Demonio.jpg', 
//'A Morte é a Única Saída - 2017.mkv','A Morte é a Única Saída - 2017.jpg', 
//'A Mosca - Remake - 1986.mkv','A Mosca - Remake - 1986.jpg', 
//'A Mosca 2 - 1989.mkv','A Mosca 2 - 1989.jpg', 
//'A Mulher de Preto 1.mkv','A Mulher de Preto 1.jpg', 
//'A Mulher de Preto 2.mkv','A Mulher de Preto 2.jpg', 
//'A Mumia - 1932.mkv','A Mumia - 1932.jpg', 
//'A Múmia - 1959.mkv','A Múmia - 1959.jpg', 
//'A Múmia - 2017.mkv','A Múmia - 2017.jpg', 
//'A Noite dos Mortos Vivos - 1990.mkv','A Noite dos Mortos Vivos - 1990.jpg', 
//'A Noite dos Mortos Vivos - Re-Animação - 2012.mkv','A Noite dos Mortos Vivos - Re-Animação - 2012.jpg', 
//'A Noite dos Mortos Vivos 3D - 2006.mkv','A Noite dos Mortos Vivos 3D - 2006.jpg', 
//'A Noiva de Frankenstein - 1935.mkv','A Noiva de Frankenstein - 1935.jpg', 
//'A Noiva do Re-Animator - 1989.mkv','A Noiva do Re-Animator - 1989.jpg', 
//'A Orfa 2.mp4','A Orfa 2.jpg', 
//'A Orfa.mp4','A Orfa.jpg', 
//'A Piramide.mp4','A Piramide.jpg', 
//'A Praga - 2006.mkv','A Praga - 2006.jpg', 
//'A Praga da Múmia - 1944.mkv','A Praga da Múmia - 1944.jpg', 
//'A Profecia - 1976.mkv','A Profecia - 1976.jpg', 
//'A Profecia 2 - 1978.mkv','A Profecia 2 - 1978.jpg', 
//'A Profecia 3 - 1981.mkv','A Profecia 3 - 1981.jpg', 
//'A Profecia 4 - 1991.mkv','A Profecia 4 - 1991.jpg', 
//'A Profecia 5 - 2006.mkv','A Profecia 5 - 2006.jpg', 
//'A Queda 2022.mkv','A Queda 2022.jpg', 
//'A Substancia.mp4','A Substancia.jpg', 
//'A Tribo - 2008.mkv','A Tribo - 2008.jpg', 
//'A Tribo 2 - 2009.mkv','A Tribo 2 - 2009.jpg', 
//'A Vingança de Jennifer.mp4','A Vingança de Jennifer.jpg', 
//'A Viúva das Sombras - 2021.mkv','A Viúva das Sombras - 2021.jpg', 
//'A Volta dos Mortos Vivos 1.mkv','A Volta dos Mortos Vivos 1.jpg', 
//'A Volta dos Mortos Vivos 2.mkv','A Volta dos Mortos Vivos 2.jpg', 
//'A Volta dos Mortos Vivos 3.mkv','A Volta dos Mortos Vivos 3.jpg', 
//'A Volta dos Mortos Vivos 4.mp4','A Volta dos Mortos Vivos 4.jpg', 
//'A Última Casa à Esquerda - Remake - 2009.mkv','A Última Casa à Esquerda - Remake - 2009.jpg', 
//'Abismo do Medo 1.mkv','Abismo do Medo 1.jpg', 
//'Abismo do Medo 2.mkv','Abismo do Medo 2.jpg', 
//'Advogado do Diabo.mp4','Advogado do Diabo.jpg', 
//'Alta Tensao.mp4','Alta Tensao.jpg', 
//'Além da Escuridao - 2012.mkv','Além da Escuridao - 2012.jpg', 
//'Além do Lago Ness - 2008.mkv','Além do Lago Ness - 2008.jpg', 
//'Anaconda 1.mkv','Anaconda 1.jpg', 
//'Anaconda 2 - 2004.mkv','Anaconda 2 - 2004.jpg', 
//'Anaconda 3 - 2008.mkv','Anaconda 3 - 2008.jpg', 
//'Anaconda 4 - 2009.mkv','Anaconda 4 - 2009.jpg', 
//'Animal - 2014.mkv','Animal - 2014.jpg', 
//'Anjo Maldito - 2009.mkv','Anjo Maldito - 2009.jpg', 
//'Anjos Rebeldes 1.mkv','Anjos Rebeldes 1.jpg', 
//'Anjos Rebeldes 2.mkv','Anjos Rebeldes 2.jpg', 
//'Anjos Rebeldes 3.mkv','Anjos Rebeldes 3.jpg', 
//'Anjos Rebeldes 4.mkv','Anjos Rebeldes 4.jpg', 
//'Anjos Rebeldes 5.mkv','Anjos Rebeldes 5.jpg', 
//'Anjos da Morte - 2006.mkv','Anjos da Morte - 2006.jpg', 
//'Annabelle 1 - 2014.mkv','Annabelle 1 - 2014.jpg', 
//'Annabelle 2 - A Criação do Mal.mkv','Annabelle 2 - A Criação do Mal.jpg', 
//'Annabelle 3 - De Volta Para Casa - 2019.mkv','Annabelle 3 - De Volta Para Casa - 2019.jpg', 
//'Aprisionados - 2015.mkv','Aprisionados - 2015.jpg', 
//'Aracnofobia - 1990.mkv','Aracnofobia - 1990.jpg', 
//'Arraste-me para o Inferno.mkv','Arraste-me para o Inferno.jpg', 
//'As Ruínas - 2008.mkv','As Ruínas - 2008.jpg', 
//'As Strippers Zumbis - 2007.mkv','As Strippers Zumbis - 2007.jpg', 
//'Asilo do Medo - 2019.mkv','Asilo do Medo - 2019.jpg', 
//'Assim na Terra Como no Inferno.mp4','Assim na Terra Como no Inferno.jpg', 
//'Atividade Paranormal 1.mp4','Atividade Paranormal 1.jpg', 
//'Atividade Paranormal 2.mkv','Atividade Paranormal 2.jpg', 
//'Atividade Paranormal 3.mp4','Atividade Paranormal 3.jpg', 
//'Atividade Paranormal 4.mp4','Atividade Paranormal 4.jpg', 
//'Atividade Paranormal 5 Marcados pelo Mal 2014.mp4','Atividade Paranormal 5 Marcados pelo Mal 2014.jpg', 
//'Atividade Paranormal 6 Dimensao Fantasma.mp4','Atividade Paranormal 6 Dimensao Fantasma.jpg', 
//'Atividade Paranormal 7 Ente Próximo.mkv','Atividade Paranormal 7 Ente Próximo.jpg', 
//'Atividade Paranormal em Toquio.mp4','Atividade Paranormal em Toquio.jpg', 
//'Através da Sombra - 2015.mkv','Através da Sombra - 2015.jpg', 
//'Aviso de Tempestade - 2007.mkv','Aviso de Tempestade - 2007.jpg', 
//'Baghead - A Bruxa dos Mortos.mp4','Baghead - A Bruxa dos Mortos.jpg', 
//'Balada Para Satã - 1971.mkv','Balada Para Satã - 1971.jpg', 
//'Banquete no Inferno 1 - 2005.mkv','Banquete no Inferno 1 - 2005.jpg', 
//'Barbarian.mp4','Barbarian.jpg', 
//'Benção Mortal - 1981.mkv','Benção Mortal - 1981.jpg', 
//'Black Water - 2007.mkv','Black Water - 2007.jpg', 
//'Boa Noite Mamae 2014.mp4','Boa Noite Mamae 2014.jpg', 
//'Boa Noite Mamae 2022.mkv','Boa Noite Mamae 2022.jpg', 
//'Bonecos da Morte (1989).mp4','Bonecos da Morte (1989).jpg', 
//'Bonecos em Guerra - O Capítulo Final (1994).mp4','Bonecos em Guerra - O Capítulo Final (1994).jpg', 
//'Bones - Anjo das Trevas - 2001.mkv','Bones - Anjo das Trevas - 2001.jpg', 
//'Brinquedos Diabólicos - 1992.mp4','Brinquedos Diabólicos - 1992.jpg', 
//'Bruxa de Blair 1.mkv','Bruxa de Blair 1.jpg', 
//'Bruxa de Blair 2.mkv','Bruxa de Blair 2.jpg', 
//'Bruxas - 2009.mkv','Bruxas - 2009.jpg', 
//'Cadaveres - 2006.mkv','Cadaveres - 2006.jpg', 
//'Cadaveres 2 - 2008.mp4','Cadaveres 2 - 2008.jpg', 
//'Cadillac Preto - 2003.mkv','Cadillac Preto - 2003.jpg', 
//'Canibais - A Tribo.mkv','Canibais - A Tribo.jpg', 
//'Carrie - A Estranha 1976.mp4','Carrie - A Estranha 1976.jpg', 
//'Cemiterio Maldito - A Origem.mp4','Cemiterio Maldito - A Origem.jpg', 
//--------------------------------------'https://archive.org/download/cemiterio-maldito-1_202507/Cemiterio Maldito 1.mp4','Cemiterio Maldito 1.jpg', 
//'Cemiterio Maldito 2.mkv','Cemiterio Maldito 2.jpg', 
//'Cemitério Maldito Remaster.mkv','Cemitério Maldito Remaster.jpg', 
//'Centopeia Humana 1.mp4','Centopeia Humana 1.jpg', 
'https://archive.org/download/centopeia-humana-2/Centopeia Humana 2.ia.mp4','Centopeia Humana 2.jpg', 
//'Centopeia Humana 3.mp4','Centopeia Humana 3.jpg', 
//'Cerdita.mp4','Cerdita.jpg', 
//'Chamado vs O Grito - 2018.mkv','Chamado vs O Grito - 2018.jpg', 
//'Chernobyl - Sinta a Radiação - 2012.mkv','Chernobyl - Sinta a Radiação - 2012.jpg', 
//'Christine O Carro Assassino.mkv','Christine O Carro Assassino.jpg', 
//'Chucky Brinquedo Assassino 1 - 1988.mkv','Chucky Brinquedo Assassino 1 - 1988.jpg', 
//'Chucky Brinquedo Assassino 2 - 1990.mkv','Chucky Brinquedo Assassino 2 - 1990.jpg', 
//'Chucky Brinquedo Assassino 3 - 1991.mkv','Chucky Brinquedo Assassino 3 - 1991.jpg', 
//'Chucky Brinquedo Assassino 4 - A Noiva de Chucky.mkv','Chucky Brinquedo Assassino 4 - A Noiva de Chucky.jpg', 
//'Chucky Brinquedo Assassino 5 - O Filho de Chucky.mkv','Chucky Brinquedo Assassino 5 - O Filho de Chucky.jpg', 
//'Chucky Brinquedo Assassino 6 - A Maldição de Chucky.mkv','Chucky Brinquedo Assassino 6 - A Maldição de Chucky.jpg', 
//'Chucky Brinquedo Assassino 7 - O Culto de Chucky.mkv','Chucky Brinquedo Assassino 7 - O Culto de Chucky.jpg', 
//'Chucky Brinquedo Assassino 8 - 2019.mkv','Chucky Brinquedo Assassino 8 - 2019.jpg', 
//'Colecionador de Ossos.mkv','Colecionador de Ossos.jpg', 
//'Colheita Maldita 1 - 1984.mkv','Colheita Maldita 1 - 1984.jpg', 
//'Colheita Maldita 2 O Sacrifício Final - 1992.mkv','Colheita Maldita 2 O Sacrifício Final - 1992.jpg', 
//'Colheita Maldita 2009.mp4','Colheita Maldita 2009.jpg', 
//'Colheita Maldita 3 - Colheita Urbana - 1995.mkv','Colheita Maldita 3 - Colheita Urbana - 1995.jpg', 
//'Colheita Maldita 4 - O Encontro- 1996.mkv','Colheita Maldita 4 - O Encontro- 1996.jpg', 
//'Colheita Maldita 5 - Campos do Terror - 1998.mkv','Colheita Maldita 5 - Campos do Terror - 1998.jpg', 
//'Colheita Maldita 6 - 666 - Isaac Está de Volta - 1999.mkv','Colheita Maldita 6 - 666 - Isaac Está de Volta - 1999.jpg', 
//'Colheita Maldita 7 Revelacao - 2001.mp4','Colheita Maldita 7 Revelacao - 2001.jpg', 
//'Colheita Maldita 8 - Genesis - 2011.mkv','Colheita Maldita 8 - Genesis - 2011.jpg', 
//'Colheita Sombria 2023.mp4','Colheita Sombria 2023.jpg', 
//'Colinas De Sangue - 2009.mkv','Colinas De Sangue - 2009.jpg', 
//'Colisão Mortal - 2016.mkv','Colisão Mortal - 2016.jpg', 
//'Comemoração Sangrenta - 2016.mkv','Comemoração Sangrenta - 2016.jpg', 
//'Conde Dracula.mkv','Conde Dracula.jpg', 
//'Continue Assistindo - 2017.mkv','Continue Assistindo - 2017.jpg', 
//'Contos do Além - 1972.mkv','Contos do Além - 1972.jpg', 
//'Corra - 2017.mkv','Corra - 2017.jpg', 
//'Corrente do Mal - 2015.mkv','Corrente do Mal - 2015.jpg', 
//'Cubo 1 - 1997.mkv','Cubo 1 - 1997.jpg', 
//'Cubo 2 - Hipercubo - 2002.mkv','Cubo 2 - Hipercubo - 2002.jpg', 
//'Cubo Zero - 2004.mkv','Cubo Zero - 2004.jpg', 
//'Cujo - 1983.mkv','Cujo - 1983.jpg', 
//'Cut - Cenas de Horror - 2000.mkv','Cut - Cenas de Horror - 2000.jpg', 
//'Cães Assassinos - 2006.mkv','Cães Assassinos - 2006.jpg', 
//'Deixe-me Entrar.mp4','Deixe-me Entrar.jpg', 
//'Despertar dos Mortos - 2011.mkv','Despertar dos Mortos - 2011.jpg', 
//'Devorador de Almas - 2006.mkv','Devorador de Almas - 2006.jpg', 
//'Dezesseis Facadas.mp4','Dezesseis Facadas.jpg', 
//'Dia dos Mortos - 1985.mkv','Dia dos Mortos - 1985.jpg', 
//'Dia dos Mortos.mp4','Dia dos Mortos.jpg', 
//'Distúrbio - 2018.mkv','Distúrbio - 2018.jpg', 
//'Diário do Mortos - 2007.mkv','Diário do Mortos - 2007.jpg', 
//'Doce Vingança 1.mkv','Doce Vingança 1.jpg', 
//'Doce Vingança 2.mkv','Doce Vingança 2.jpg', 
//'Doce Vingança 3.mkv','Doce Vingança 3.jpg', 
//'Doce Vingança 4.mp4','Doce Vingança 4.jpg', 
//'Domínio- Prequela do Exorcista - 2005.mp4','Domínio- Prequela do Exorcista - 2005.jpg', 
//'Doutor Sono.mkv','Doutor Sono.jpg', 
//'Dracula 1931.mkv','Dracula 1931.jpg', 
//'Dragão Vermelho - 2002.mkv','Dragão Vermelho - 2002.jpg', 
//'Drive-Thru - Fast Food Da Morte - 2007.mkv','Drive-Thru - Fast Food Da Morte - 2007.jpg', 
//'Drácula de Bram Stoker - 1992.mkv','Drácula de Bram Stoker - 1992.jpg', 
//'Elvira - A Rainha das Trevas - 1988.mkv','Elvira - A Rainha das Trevas - 1988.jpg', 
//'Elvira - As Loucas Aventuras de Elvira - 2001.mkv','Elvira - As Loucas Aventuras de Elvira - 2001.jpg', 
//'Enigmas de um Crime 2010.mp4','Enigmas de um Crime 2010.jpg', 
//'Enjaulada 2016.mp4','Enjaulada 2016.jpg', 
//'Enterrado Vivo.mp4','Enterrado Vivo.jpg', 
//'Entrevista com Vampiros - 1994.mkv','Entrevista com Vampiros - 1994.jpg', 
//'Escada de Jaco.mp4','Escada de Jaco.jpg', 
//'Escuridão - 2005.mkv','Escuridão - 2005.jpg', 
//'Espelho do Medo 1 - 2008.mkv','Espelho do Medo 1 - 2008.jpg', 
//'Espelho do Medo 2 - 2010.mkv','Espelho do Medo 2 - 2010.jpg', 
//'Espinhos - 2008.mkv','Espinhos - 2008.jpg', 
//'Espíritos 1 - A Morte Está ao Seu Lado - 2004.mkv','Espíritos 1 - A Morte Está ao Seu Lado - 2004.jpg', 
//'Espíritos 2 - Você Nunca Está Sozinho - 2006.mkv','Espíritos 2 - Você Nunca Está Sozinho - 2006.jpg', 
//'Esquizofrenia - 1980.mkv','Esquizofrenia - 1980.jpg', 
//'Estrada Maldita - 2007.mkv','Estrada Maldita - 2007.jpg', 
//'Eu Ainda Sei O Que Vocês Fizeram No Verão Passado - 1998.mkv','Eu Ainda Sei O Que Vocês Fizeram No Verão Passado - 1998.jpg', 
//'Eu Sei O Que Vocês Fizeram No Verão Passado - 1997.mkv','Eu Sei O Que Vocês Fizeram No Verão Passado - 1997.jpg', 
//'Eu Sempre Vou Saber o Que Vocês Fizeram no Verão Passado - 2006.mkv','Eu Sempre Vou Saber o Que Vocês Fizeram no Verão Passado - 2006.jpg', 
//'Eu vi o brilho da TV.mp4','Eu vi o brilho da TV.jpg', 
//'Evocando Espíritos 1 - 2009.mkv','Evocando Espíritos 1 - 2009.jpg', 
//'Experimentos Macabros 2022.mp4','Experimentos Macabros 2022.jpg', 
//'Faces do Medo - 2013.mkv','Faces do Medo - 2013.jpg', 
//'Fale Comigo 2023.mkv','Fale Comigo 2023.jpg', 
//'Familia Addams.mkv','Familia Addams.jpg', 
//'Fantasma 1 - 1979.mkv','Fantasma 1 - 1979.jpg', 
//'Fantasma 2 - 1988.mkv','Fantasma 2 - 1988.jpg', 
//'Fantasma 3 - 1994.mkv','Fantasma 3 - 1994.jpg', 
//'Fantasma 4 - 1998.mkv','Fantasma 4 - 1998.jpg', 
//'Filha da Luz.mp4','Filha da Luz.jpg', 
//'Fome Animal - 1992.mkv','Fome Animal - 1992.jpg', 
//'Frankenstein Encontra o Lobisomem - 1943.mkv','Frankenstein Encontra o Lobisomem - 1943.jpg', 
//'Freddy vs Jason.mkv','Freddy vs Jason.jpg', 
//'Fuga Sobre Trilhos - 2008.mkv','Fuga Sobre Trilhos - 2008.jpg', 
//'Girl - 2020.mkv','Girl - 2020.jpg', 
//'Gritos Mortais.mkv','Gritos Mortais.jpg', 
//'Gritos do Além 2011.mp4','Gritos do Além 2011.jpg', 
//'Grotesco 2009.mp4','Grotesco 2009.jpg', 
//'Halloween a1 A Noite do Terror.mkv','Halloween a1 A Noite do Terror.jpg', 
//'Halloween b2 O Pesadelo Continua.mkv','Halloween b2 O Pesadelo Continua.jpg', 
//'Halloween c3 A Noite das Bruxas.mkv','Halloween c3 A Noite das Bruxas.jpg', 
//'Halloween d4 O Retorno de Michael Myers.mkv','Halloween d4 O Retorno de Michael Myers.jpg', 
//'Halloween e5 A Vingança de Michael Myers.mkv','Halloween e5 A Vingança de Michael Myers.jpg', 
//'Halloween f6 A Última Vingança.mkv','Halloween f6 A Última Vingança.jpg', 
//'Halloween g7 H20.mkv','Halloween g7 H20.jpg', 
//'Halloween h8 - Ressurreição.mkv','Halloween h8 - Ressurreição.jpg', 
//'Halloween i9 - O Inicio.mkv','Halloween i9 - O Inicio.jpg', 
//'Halloween j10 2.mkv','Halloween j10 2.jpg', 
//'Halloween k11 2018.mkv','Halloween k11 2018.jpg', 
//'Halloween l12 Kills.mkv','Halloween l12 Kills.jpg', 
//'Halloween m13 Ends.mp4','Halloween m13 Ends.jpg', 
//'Halloween m14 Ends 2022.mp4','Halloween m14 Ends 2022.jpg', 
//'Hannibal - 2001.mkv','Hannibal - 2001.jpg', 
//'Hannibal - A Origem do Mal - 2007.mkv','Hannibal - A Origem do Mal - 2007.jpg', 
//'Hellraiser 1 Renascido do Inferno.mp4','Hellraiser 1 Renascido do Inferno.jpg', 
//'Hellraiser 10 2022.mkv','Hellraiser 10 2022.jpg', 
//'Hellraiser 2 Renascido das Trevas.mp4','Hellraiser 2 Renascido das Trevas.jpg', 
//'Hellraiser 3 Inferno na Terra.mp4','Hellraiser 3 Inferno na Terra.jpg', 
//'Hellraiser 4 Herança Maldita.mp4','Hellraiser 4 Herança Maldita.jpg', 
//'Hellraiser 5 Inferno.mp4','Hellraiser 5 Inferno.jpg', 
//'Hellraiser 6 Cacador do Inferno.mp4','Hellraiser 6 Cacador do Inferno.jpg', 
//'Hellraiser 7 O Retorno dos Mortos.mp4','Hellraiser 7 O Retorno dos Mortos.jpg', 
//'Hellraiser 8 O Mundo do Inferno.mp4','Hellraiser 8 O Mundo do Inferno.jpg', 
//'Hellraiser 9 Revelacoes.mp4','Hellraiser 9 Revelacoes.jpg', 
//'Hellraiser O Julgamento.mp4','Hellraiser O Julgamento.jpg', 
//'Hereditário - 2018.mkv','Hereditário - 2018.jpg', 
//'Herege.mp4','Herege.jpg', 
//'Histeria - 2000.mkv','Histeria - 2000.jpg', 
//'Holocausto Canibal.mkv','Holocausto Canibal.jpg', 
//'Horas de Medo -2010.mkv','Horas de Medo -2010.jpg', 
//'Hush - A Morte Ouve - 2016.mkv','Hush - A Morte Ouve - 2016.jpg', 
//'Ilha dos Mortos - 2009.mkv','Ilha dos Mortos - 2009.jpg', 
//'Imagens do Além - 2008.mkv','Imagens do Além - 2008.jpg', 
//'Instinto Assassino - 1991.mkv','Instinto Assassino - 1991.jpg', 
//'Invasores - 2007.mkv','Invasores - 2007.jpg', 
//'Invasores de Corpos - 1993.mkv','Invasores de Corpos - 1993.jpg', 
//'Invasão Zumbi 1 - 2016.mkv','Invasão Zumbi 1 - 2016.jpg', 
//'Invasão Zumbi 2 - Peninsula - 2020.mkv','Invasão Zumbi 2 - Peninsula - 2020.jpg', 
//'Invocação do Mal 1 - 2013.mkv','Invocação do Mal 1 - 2013.jpg', 
//'Invocação do Mal 2 - 2016.mkv','Invocação do Mal 2 - 2016.jpg', 
//'Invocação do Mal 3 - A Ordem do Demônio - 2021.mkv','Invocação do Mal 3 - A Ordem do Demônio - 2021.jpg', 
//'Irmãs Diabólicas - 1972.mkv','Irmãs Diabólicas - 1972.jpg', 
//'Irreversivel.mp4','Irreversivel.jpg', 
//'It 1 - 2017.mkv','It 1 - 2017.jpg', 
//'It 2 - 2019.mkv','It 2 - 2019.jpg', 
//'It- Uma obra prima do medo.mp4','It- Uma obra prima do medo.jpg', 
//'Jack Frost 1 - 1997.mkv','Jack Frost 1 - 1997.jpg', 
//'Jason X - 2001.mkv','Jason X - 2001.jpg', 
//'Jogo Macabro.mkv','Jogo Macabro.jpg', 
'https://archive.org/download/jogos-mortais-1_202507/Jogos Mortais 1.mp4','Jogos Mortais 1.jpg', 
//'Jogos Mortais 10.mp4','Jogos Mortais 10.jpg', 
//'Jogos Mortais 2.mkv','Jogos Mortais 2.jpg', 
//'Jogos Mortais 3.mkv','Jogos Mortais 3.jpg', 
//'Jogos Mortais 4.mkv','Jogos Mortais 4.jpg', 
//'Jogos Mortais 5.mkv','Jogos Mortais 5.jpg', 
//'Jogos Mortais 6.mkv','Jogos Mortais 6.jpg', 
//'Jogos Mortais 7.mkv','Jogos Mortais 7.jpg', 
//'Jogos Mortais 8.mkv','Jogos Mortais 8.jpg', 
//'Jogos Mortais 9 - Espiral - O Legado de Jogos Mortais.mkv','Jogos Mortais 9 - Espiral - O Legado de Jogos Mortais.jpg', 
//'Laranja Mecanica.mp4','Laranja Mecanica.jpg', 
//'Leatherface Massacre no Texas.mp4','Leatherface Massacre no Texas.jpg', 
//'Lenda Urbana 1 - 1998.mkv','Lenda Urbana 1 - 1998.jpg', 
//'Lenda Urbana 2 - 2000.mkv','Lenda Urbana 2 - 2000.jpg', 
//'Lenda Urbana 3 - 2005.mkv','Lenda Urbana 3 - 2005.jpg', 
//'Lendas do Além-Túmulo - 1995.mkv','Lendas do Além-Túmulo - 1995.jpg', 
//'Lendas do Além-Túmulo - 1996.mkv','Lendas do Além-Túmulo - 1996.jpg', 
//'Lendas do Além-Túmulo - 2000.mkv','Lendas do Além-Túmulo - 2000.jpg', 
//'Livrai-nos do Mal.mp4','Livrai-nos do Mal.jpg', 
//'Lobisomem Americano em Londres - 1981.mkv','Lobisomem Americano em Londres - 1981.jpg', 
//'Lobisomem Americano em Paris - 1997.mkv','Lobisomem Americano em Paris - 1997.jpg', 
//'Longlegs.mp4','Longlegs.jpg', 
//'M3gan.mp4','M3gan.jpg', 
//'Malditas Aranhas - 2002.mkv','Malditas Aranhas - 2002.jpg',  
//'Maligno - 2022.mp4','Maligno - 2022.jpg', 
//'Maligno 2019.mp4','Maligno 2019.jpg', 
//'Mama - 2013.mkv','Mama - 2013.jpg', 
//'Martyrs - 2008.mp4','Martyrs - 2008.jpg', 
//'Martyrs - 2015.mkv','Martyrs - 2015.jpg', 
//'Martyrs - 2015.mp4','Martyrs - 2015.jpg', 
//'Martyrs Lane.mp4','Martyrs Lane.jpg', 
//'Maya O Ritual do Fogo.mp4','Maya O Ritual do Fogo.jpg', 
//'Megan is Missing.mp4','Megan is Missing.jpg', 
//'Menina Ma Com 2005.mp4','Menina Ma Com 2005.jpg', 
//'Mestre dos Desejos 1.mkv','Mestre dos Desejos 1.jpg', 
//'Mestre dos Desejos 2.mkv','Mestre dos Desejos 2.jpg', 
//'Mestre dos Desejos 3.mkv','Mestre dos Desejos 3.jpg', 
//'Mestre dos Desejos 4.mkv','Mestre dos Desejos 4.jpg', 
//'Midsommar.mp4','Midsommar.jpg', 
//'Minotauro - 2006.mkv','Minotauro - 2006.jpg', 
//'Monstro do Armario.mkv','Monstro do Armario.jpg', 
//'Morte Morte Morte.mp4','Morte Morte Morte.jpg', 
//'Morte Súbita - 2007.mkv','Morte Súbita - 2007.jpg', 
//'Mortuária - 2005.mkv','Mortuária - 2005.jpg', 
//'Mother - 2017.mkv','Mother - 2017.jpg', 
//'Mutação 1 - 1997.mkv','Mutação 1 - 1997.jpg', 
//'Mutação 2 - 2001.mkv','Mutação 2 - 2001.jpg', 
//'Mutação 3 - O Sentinela - 2003.mkv','Mutação 3 - O Sentinela - 2003.jpg', 
//'Mutilados - 2006.mkv','Mutilados - 2006.jpg', 
//'Nao Desligue 2016.mkv','Nao Desligue 2016.jpg', 
//'Nasce um Monstro 1 - 1974.mkv','Nasce um Monstro 1 - 1974.jpg', 
//'Nasce um Monstro 2 - 1978.mkv','Nasce um Monstro 2 - 1978.jpg', 
//'Nasce um Monstro 3 - 1987.mkv','Nasce um Monstro 3 - 1987.jpg', 
//'Navio Fantasma.mp4','Navio Fantasma.jpg', 
//'Nefarious.mp4','Nefarious.jpg', 
//'Ninguem Sobrevive.mp4','Ninguem Sobrevive.jpg', 
//'Noite das Bruxas Macabra - 2014.mkv','Noite das Bruxas Macabra - 2014.jpg', 
//'Noite de Halloween - 2006.mkv','Noite de Halloween - 2006.jpg', 
//'Noite do Terror 1 - 2006.mkv','Noite do Terror 1 - 2006.jpg', 
//'Noite do Terror 2 - 2014.mkv','Noite do Terror 2 - 2014.jpg', 
//'Nos - 2019.mp4','Nos - 2019.jpg', 
//'Nosferatu 1922.mp4','Nosferatu 1922.jpg', 
//'Não Adianta Fugir - 2009.mkv','Não Adianta Fugir - 2009.jpg', 
//'Não Olhe - 2019.mkv','Não Olhe - 2019.jpg', 
//'O Abominavel Dr. Phibes.mp4','O Abominavel Dr. Phibes.jpg', 
//'O Albergue 1.mkv','O Albergue 1.jpg', 
//'O Albergue 2.mkv','O Albergue 2.jpg', 
//'O Albergue 3.mkv','O Albergue 3.jpg', 
//'O Atalho - 2013.mkv','O Atalho - 2013.jpg', 
//'O Ataque dos Vermes Malditos 2.mp4','O Ataque dos Vermes Malditos 2.jpg', 
//'O Ataque dos Vermes Malditos 3.mkv','O Ataque dos Vermes Malditos 3.jpg', 
//'O Ataque dos Vermes Malditos 4 - O Começo da Lenda.mkv','O Ataque dos Vermes Malditos 4 - O Começo da Lenda.jpg', 
//'O Ataque dos Vermes Malditos 5 Linhas de Sangue.mkv','O Ataque dos Vermes Malditos 5 Linhas de Sangue.jpg', 
//'O Ataque dos Vermes Malditos 6 Um Dia Frio no Inferno 2018.mp4','O Ataque dos Vermes Malditos 6 Um Dia Frio no Inferno 2018.jpg', 
//'O Ataque dos Vermes Malditos 7- Ilha dos Shriekers 2020.mkv','O Ataque dos Vermes Malditos 7- Ilha dos Shriekers 2020.jpg', 
//'O Bar Luva Dourada 2019.mp4','O Bar Luva Dourada 2019.jpg', 
//'O Bebê de Rosemary 1968.mp4','O Bebê de Rosemary 1968.jpg', 
//'O Bosque - 2008.mkv','O Bosque - 2008.jpg', 
//'O Bosque de Blair Witch.mp4','O Bosque de Blair Witch.jpg', 
//'O Castelo Maldito - 1995.mkv','O Castelo Maldito - 1995.jpg', 
//'O Cativeiro - 2010.mkv','O Cativeiro - 2010.jpg', 
//'O Caçador De Cabeças - 1988.mkv','O Caçador De Cabeças - 1988.jpg', 
//'O Chale - 2019.mkv','O Chale - 2019.jpg', 
//'O Chamado 1.mkv','O Chamado 1.jpg', 
//'O Chamado 2.mkv','O Chamado 2.jpg', 
//'O Chamado 3.mkv','O Chamado 3.jpg', 
//'O Chamado 4.mp4','O Chamado 4.jpg', 
//'O Chupa-Cabra - 2014.mkv','O Chupa-Cabra - 2014.jpg', 
//'O Colecionador de Corpos.mp4','O Colecionador de Corpos.jpg', 
//'O Crematorio.mp4','O Crematorio.jpg', 
//'O Culto - 2017.mkv','O Culto - 2017.jpg', 
//'O Cão do Diabo - 1978.mkv','O Cão do Diabo - 1978.jpg', 
//'O Dentista 1.mkv','O Dentista 1.jpg', 
//'O Dentista 2.mkv','O Dentista 2.jpg', 
//'O Discipulo de Dracula.mkv','O Discipulo de Dracula.jpg', 
//'O Enigma do Outro Mundo.mkv','O Enigma do Outro Mundo.jpg', 
//'O Exorcismo de Emily Rose.mp4','O Exorcismo de Emily Rose.jpg', 
//'O Exorcista - O Devoto 2023.mp4','O Exorcista - O Devoto 2023.jpg', 
//'O Exorcista 1.mkv','O Exorcista 1.jpg', 
//'O Exorcista 2.mp4','O Exorcista 2.jpg', 
//'O Exorcista 3.mp4','O Exorcista 3.jpg', 
//'O Exorcista 4.mkv','O Exorcista 4.jpg', 
//'O Exorcista do Papa.mp4','O Exorcista do Papa.jpg', 
//'O Fantasma da Opera 1962.mkv','O Fantasma da Opera 1962.jpg', 
//'O Farol.mkv','O Farol.jpg', 
//'O Filho de Frankenstein - 1939.mkv','O Filho de Frankenstein - 1939.jpg', 
//'O Grande Predador - 2007.mkv','O Grande Predador - 2007.jpg', 
//'O Grito 1 - 2004.mkv','O Grito 1 - 2004.jpg', 
//'O Grito 2 - 2006.mkv','O Grito 2 - 2006.jpg', 
//'O Grito 3 - 2009.mkv','O Grito 3 - 2009.jpg', 
//'O Grito 4 - 2020.mkv','O Grito 4 - 2020.jpg', 
//'O Homem Invisível - 2020.mkv','O Homem Invisível - 2020.jpg', 
//'O Homem Sem Sombra 1 - 2000.mkv','O Homem Sem Sombra 1 - 2000.jpg', 
//'O Homem Sem Sombra 2 - 2008.mkv','O Homem Sem Sombra 2 - 2008.jpg', 
//------------------------'https://archive.org/download/o-iluminado_202507/O Iluminado.mp4','O Iluminado.jpg', 
//'O Internato - 2018.mkv','O Internato - 2018.jpg', 
//'O Limite do Medo.mp4','O Limite do Medo.jpg', 
//'O Lobisomem - 1941.mkv','O Lobisomem - 1941.jpg', 
//'O Lobisomem - 2010.mkv','O Lobisomem - 2010.jpg', 
'https://archive.org/download/o-massacre-da-serra-eletrica-1/O Massacre Da Serra Elétrica 1.mp4','O Massacre Da Serra Elétrica 1.jpg', 
//'O Massacre Da Serra Elétrica 2.mkv','O Massacre Da Serra Elétrica 2.jpg', 
//'O Massacre Da Serra Elétrica 2003.mp4','O Massacre Da Serra Elétrica 2003.jpg', 
//'O Massacre Da Serra Elétrica 3 1990.mkv','O Massacre Da Serra Elétrica 3 1990.jpg', 
//'O Massacre Da Serra Elétrica Inicio.mp4','O Massacre Da Serra Elétrica Inicio.jpg', 
//'O Massacre da Serra Eletrica 3D.mp4','O Massacre da Serra Eletrica 3D.jpg', 
//'O Massacre da Serra Elétrica 2022.mkv','O Massacre da Serra Elétrica 2022.jpg', 
//'O Menu 2022.mp4','O Menu 2022.jpg', 
//'O Mestre dos Brinquedos 2 A Volta do Mestre dos Brinquedos 1990.mp4','O Mestre dos Brinquedos 2 A Volta do Mestre dos Brinquedos 1990.jpg', 
//'O Mestre dos Brinquedos 3 - A Vingança de Toulon (1991).mp4','O Mestre dos Brinquedos 3 - A Vingança de Toulon (1991).jpg', 
//'O Mestre dos Brinquedos 4 - Bonecos em Guerra (1993).mp4','O Mestre dos Brinquedos 4 - Bonecos em Guerra (1993).jpg', 
//'O Misterio da Passagem da Morte 2013.mp4','O Misterio da Passagem da Morte 2013.jpg', 
//'O Mistério das Duas Irmãs - 2009.mkv','O Mistério das Duas Irmãs - 2009.jpg', 
//'O Monstro da Neve.mkv','O Monstro da Neve.jpg', 
//'O Monstro do Armario.mp4','O Monstro do Armario.jpg', 
//'O Monstro do Artico - 1951.mkv','O Monstro do Artico - 1951.jpg', 
//'O Nevoeiro - 2007.mkv','O Nevoeiro - 2007.jpg', 
//'O Olho do Mal - 2008.mkv','O Olho do Mal - 2008.jpg', 
//'O Outro Lado do Lago.mp4','O Outro Lado do Lago.jpg', 
//'O Pacto.mp4','O Pacto.jpg', 
//'O Pesadelo 1 - 2005.mkv','O Pesadelo 1 - 2005.jpg', 
//'O Pesadelo 2 - 2007.mkv','O Pesadelo 2 - 2007.jpg', 
//'O Pesadelo 3 - 2008.mkv','O Pesadelo 3 - 2008.jpg', 
//'O Poco 2.mp4','O Poco 2.jpg', 
//'O Poco.mkv','O Poco.jpg', 
//'O Portal - 2005.mkv','O Portal - 2005.jpg', 
//'O Porão - 1989.mkv','O Porão - 1989.jpg', 
//'O Ritual - 2017.mkv','O Ritual - 2017.jpg', 
//'O Sacrifício - 2006.mkv','O Sacrifício - 2006.jpg', 
//'O Sangue do Dracula.mkv','O Sangue do Dracula.jpg', 
//'O Segredo da Cabana - 2012.mkv','O Segredo da Cabana - 2012.jpg', 
//'O Telefone Preto 2022.mkv','O Telefone Preto 2022.jpg', 
//'O massacre da serra elétrica 4 O retorno.mp4','O massacre da serra elétrica 4 O retorno.jpg', 
//'O Último Exorcismo - Parte 1 - 2010.mkv','O Último Exorcismo - Parte 1 - 2010.jpg', 
//'O Último Exorcismo - Parte 2 - 2013.mkv','O Último Exorcismo - Parte 2 - 2013.jpg', 
//'Olhos Assassinos - 1981.mkv','Olhos Assassinos - 1981.jpg', 
//'Olhos Famintos 1.mkv','Olhos Famintos 1.jpg', 
//'Olhos Famintos 2.mkv','Olhos Famintos 2.jpg', 
//'Olhos Famintos 3.mkv','Olhos Famintos 3.jpg', 
//'Olhos Famintos 4.mp4','Olhos Famintos 4.jpg', 
//'Os 3 Infernais - 2019.mkv','Os 3 Infernais - 2019.jpg', 
//'Os Escravos de Satanás - 2018.mkv','Os Escravos de Satanás - 2018.jpg', 
//'Os Esquecidos.mkv','Os Esquecidos.jpg', 
//'Os Estranhos - 2008.mkv','Os Estranhos - 2008.jpg', 
//'Os Estranhos - Caçada Noturna - 2018.mkv','Os Estranhos - Caçada Noturna - 2018.jpg', 
//'Os Mensageiros 1 - 2007.mkv','Os Mensageiros 1 - 2007.jpg', 
//'Os Mensageiros 2 - 2009.mkv','Os Mensageiros 2 - 2009.jpg', 
//'Os Mortos Não Morrem - 2019.mkv','Os Mortos Não Morrem - 2019.jpg', 
//'Os Pássaros 1 - 1963.mkv','Os Pássaros 1 - 1963.jpg', 
//'Os Pássaros 2 - O Ataque Final.mp4','Os Pássaros 2 - O Ataque Final.jpg', 
//'Os Órfãos - 2020.mkv','Os Órfãos - 2020.jpg', 
//'Outra Alma.mp4','Outra Alma.jpg', 
//'Pague Para Entrar e Reze Para Sair - 1981.mkv','Pague Para Entrar e Reze Para Sair - 1981.jpg', 
//'Palhaços Assassinos do Espaço Sideral - 1988.mkv','Palhaços Assassinos do Espaço Sideral - 1988.jpg', 
//'Palhaços Infernais - 2017.mkv','Palhaços Infernais - 2017.jpg', 
//'Panico 1.mkv','Panico 1.jpg', 
//'Panico 2.mkv','Panico 2.jpg', 
//'Panico 3.mkv','Panico 3.jpg', 
//'Panico 4.mkv','Panico 4.jpg', 
//'Panico 5.mp4','Panico 5.jpg', 
//'Panico 6.mp4','Panico 6.jpg', 
//'Paranóia - 2007.mkv','Paranóia - 2007.jpg', 
//'Passaro Pintado.mp4','Passaro Pintado.jpg', 
//'Pearl.mkv','Pearl.jpg', 
//'Perseguidos - 2010.mkv','Perseguidos - 2010.jpg', 
//'Perseguidos pela Morte - 2014.mkv','Perseguidos pela Morte - 2014.jpg', 
//'Perseguição 1 - 2001.mkv','Perseguição 1 - 2001.jpg', 
//'Perseguição 2 - O Resgate - 2008.mkv','Perseguição 2 - O Resgate - 2008.jpg', 
//'Perseguição 3 - Correndo Para a Morte - 2014.mkv','Perseguição 3 - Correndo Para a Morte - 2014.jpg', 
//'Pesadelos do Passado 1 - 2012.mkv','Pesadelos do Passado 1 - 2012.jpg', 
//'Pesadelos do Passado 2 - 2014.mkv','Pesadelos do Passado 2 - 2014.jpg', 
//'Pink Flamingo.mp4','Pink Flamingo.jpg', 
//'Piranha 1 - 2010.mkv','Piranha 1 - 2010.jpg', 
//'Piranha 2 - 2012.mkv','Piranha 2 - 2012.jpg', 
//'Poltergeist 1 - 1982.mkv','Poltergeist 1 - 1982.jpg', 
//'Poltergeist 2 - 1986.mkv','Poltergeist 2 - 1986.jpg', 
//'Poltergeist 3 - 1988.mkv','Poltergeist 3 - 1988.jpg', 
//'Poltergeist 4 - O Fenômeno - 2015.mkv','Poltergeist 4 - O Fenômeno - 2015.jpg', 
//'Premonição 1 - 2000.mkv','Premonição 1 - 2000.jpg', 
//'Premonição 2 - 2003.mkv','Premonição 2 - 2003.jpg', 
//'Premonição 3 - 2006.mkv','Premonição 3 - 2006.jpg', 
//'Premonição 4 - 2009.mkv','Premonição 4 - 2009.jpg', 
//'Premonição 5 - 2011.mkv','Premonição 5 - 2011.jpg', 
//'Primitivo - 2007.mkv','Primitivo - 2007.jpg', 
//'Psicopata Americano 2.mkv','Psicopata Americano 2.jpg', 
//'Psicopata Americano.mkv','Psicopata Americano.jpg', 
//'Psicose - Remake - 1998.mkv','Psicose - Remake - 1998.jpg', 
//'Psicose 1 - 1960.mkv','Psicose 1 - 1960.jpg', 
//'Psicose 2 - 1983.mkv','Psicose 2 - 1983.jpg', 
//'Psicose 3 - 1986.mkv','Psicose 3 - 1986.jpg', 
//'Psicose 4 - O Começo - 1990.mkv','Psicose 4 - O Começo - 1990.jpg', 
//'Pumpkinhead - 1988.mkv','Pumpkinhead - 1988.jpg', 
//'Pumpkinhead 2 - 1994.mkv','Pumpkinhead 2 - 1994.jpg', 
//'Pânico Na Floresta 6.mp4','Pânico Na Floresta 6.jpg', 
//'Pânico na Floresta 1.mp4','Pânico na Floresta 1.jpg', 
//'Pânico na Floresta 2.mp4','Pânico na Floresta 2.jpg', 
//'Pânico na Floresta 3.mkv','Pânico na Floresta 3.jpg', 
//'Pânico na Floresta 4.mp4','Pânico na Floresta 4.jpg', 
//'Pânico na Floresta 5.mp4','Pânico na Floresta 5.jpg', 
//'Pânico na Floresta 7 - A Fundação.mp4','Pânico na Floresta 7 - A Fundação.jpg', 
//'Pânico na Ilha - 2009.mkv','Pânico na Ilha - 2009.jpg', 
//'Pânico no Deserto 1 - 2005.mkv','Pânico no Deserto 1 - 2005.jpg', 
//'Pânico no Deserto 2 - 2008.mkv','Pânico no Deserto 2 - 2008.jpg', 
//'Pânico no Lago 1 - 1999.mkv','Pânico no Lago 1 - 1999.jpg', 
//'Pânico no Lago 2 - 2007.mkv','Pânico no Lago 2 - 2007.jpg', 
//'Pânico no Lago 3 - 2010.mkv','Pânico no Lago 3 - 2010.jpg', 
//'Pânico no Lago 4 - 2012.mkv','Pânico no Lago 4 - 2012.jpg', 
//'Pânico no Lago 5 - O Legado - 2018.mkv','Pânico no Lago 5 - O Legado - 2018.jpg', 
//'Pânico no Lago vs. Anaconta.mkv','Pânico no Lago vs. Anaconta.jpg', 
//'Quarentena 1 - Remake - 2008.mkv','Quarentena 1 - Remake - 2008.jpg', 
//'Quarentena 2 - Terminal - 2011.mkv','Quarentena 2 - Terminal - 2011.jpg', 
//'REC 1.mkv','REC 1.jpg', 
//'REC 2.mkv','REC 2.jpg', 
//'REC 3.mkv','REC 3.jpg', 
//'REC 4.mkv','REC 4.jpg', 
//'Re-Animator - 1985.mkv','Re-Animator - 1985.jpg', 
//'Re-Animator - Fase Terminal - 2003.mkv','Re-Animator - Fase Terminal - 2003.jpg', 
//'Refém do Espirito - 2008.mkv','Refém do Espirito - 2008.jpg', 
//'Rejeitados pelo Diabo - 2005.mkv','Rejeitados pelo Diabo - 2005.jpg', 
//'Resident Evil - A Vingança - 2017.mkv','Resident Evil - A Vingança - 2017.jpg', 
//'Resident Evil - Condenação - 2012.mkv','Resident Evil - Condenação - 2012.jpg', 
//'Resident Evil 1 - Hóspede Maldito - 2002.mkv','Resident Evil 1 - Hóspede Maldito - 2002.jpg', 
//'Resident Evil 2 - Apocalipse - 2004.mkv','Resident Evil 2 - Apocalipse - 2004.jpg', 
//'Resident Evil 3 - A Extinção - 2007.mkv','Resident Evil 3 - A Extinção - 2007.jpg', 
//'Resident Evil 4 - Recomeço - 2010.mkv','Resident Evil 4 - Recomeço - 2010.jpg', 
//'Resident Evil 5 - Retribuição - 2012.mkv','Resident Evil 5 - Retribuição - 2012.jpg', 
//'Resident Evil 6 - O Capítulo Final - 2017.mkv','Resident Evil 6 - O Capítulo Final - 2017.jpg', 
//'Ripper - O Mensageiro do Inferno - 2001.mkv','Ripper - O Mensageiro do Inferno - 2001.jpg', 
//'Ripper 2 - Ressuscitando o Medo - 2004.mp4','Ripper 2 - Ressuscitando o Medo - 2004.jpg', 
//'Rogai por Nos.mp4','Rogai por Nos.jpg', 
//'Rota Mortal 1 - 2006.mkv','Rota Mortal 1 - 2006.jpg', 
//'Rota Mortal 2 - Não Olhe Para Trás - 2008.mkv','Rota Mortal 2 - Não Olhe Para Trás - 2008.jpg', 
//'Rota da Morte.mp4','Rota da Morte.jpg', 
//'Rua do Medo 1 - 1994.mkv','Rua do Medo 1 - 1994.jpg', 
//'Rua do Medo 2 - 1978.mkv','Rua do Medo 2 - 1978.jpg', 
//'Rua do Medo 3 - 1666.mkv','Rua do Medo 3 - 1666.jpg', 
//'Sanatorio - 2013.mkv','Sanatorio - 2013.jpg',
//'Seed - Assassino em Serie - 2006.mkv','Seed - Assassino em Serie - 2006.jpg', 
//'Seed 2 - A Nova Geração - 2014.mkv','Seed 2 - A Nova Geração - 2014.jpg', 
//'Semente Do Diabo - 1979.mkv','Semente Do Diabo - 1979.jpg', 
//'Sepultado Vivo - 1990.mkv','Sepultado Vivo - 1990.jpg', 
//'Sepultado Vivo 2.mp4','Sepultado Vivo 2.jpg', 
//'Serbian Film.mp4','Serbian Film.jpg', 
//'Seres Rastejantes - 2006.mkv','Seres Rastejantes - 2006.jpg', 
//'Seven - Sete Pecados Capitais.mp4','Seven - Sete Pecados Capitais.jpg', 
//'Sexta-Feira 13 - Parte 1.mp4','Sexta-Feira 13 - Parte 1.jpg', 
//'Sexta-Feira 13 - Parte 2.mp4','Sexta-Feira 13 - Parte 2.jpg', 
//'Sexta-Feira 13 - Parte 3.mp4','Sexta-Feira 13 - Parte 3.jpg', 
//'Sexta-Feira 13 - Parte 4 - O Capítulo Final.mp4','Sexta-Feira 13 - Parte 4 - O Capítulo Final.jpg', 
//'Sexta-Feira 13 - Parte 5 - Um Novo Recomeço.mp4','Sexta-Feira 13 - Parte 5 - Um Novo Recomeço.jpg', 
//'Sexta-Feira 13 - Parte 6- Jason Vive.mp4','Sexta-Feira 13 - Parte 6- Jason Vive.jpg', 
//'Sexta-Feira 13 - Parte 7- A Matança Continua.mp4','Sexta-Feira 13 - Parte 7- A Matança Continua.jpg', 
//'Sexta-Feira 13 - Parte 8- Jason Ataca Nova York.mp4','Sexta-Feira 13 - Parte 8- Jason Ataca Nova York.jpg', 
//'Sexta-Feira 13 - Parte 9.mp4','Sexta-Feira 13 - Parte 9.jpg', 
//'Sexta-Feira 13 2009.mp4','Sexta-Feira 13 2009.jpg', 
//'Shakma - A Fúria Assassina - 1990.mkv','Shakma - A Fúria Assassina - 1990.jpg', 
//'Siga o Mestre - 2006.mkv','Siga o Mestre - 2006.jpg', 
//'Silent Hill - Revelações - 2012.mkv','Silent Hill - Revelações - 2012.jpg', 
//'Sinais.mp4','Sinais.jpg', 
//'Skinamarink.mp4','Skinamarink.jpg', 
//'Slender Man - O Pesadelo sem Façe.mkv','Slender Man - O Pesadelo sem Façe.jpg', 
//'Sobrenatural 1 - 2010.mkv','Sobrenatural 1 - 2010.jpg', 
//'Sobrenatural 2 - 2014.mkv','Sobrenatural 2 - 2014.jpg', 
//'Sobrenatural 3 - A Origem - 2015.mkv','Sobrenatural 3 - A Origem - 2015.jpg', 
//'Sobrenatural 4 - A última Chave - 2018.mkv','Sobrenatural 4 - A última Chave - 2018.jpg', 
//'Sobrenatural 5.mp4','Sobrenatural 5.jpg', 
//'Sorria 2.mp4','Sorria 2.jpg', 
//'Sorria.mp4','Sorria.jpg', 
//'Sozinha.mp4','Sozinha.jpg', 
//'Spawn - O Soldado do Inferno.mp4','Spawn - O Soldado do Inferno.jpg', 
//'Splice A Nova Espécie.mp4','Splice A Nova Espécie.jpg', 
//'Stairs.mp4','Stairs.jpg', 
//'Stigmata.mkv','Stigmata.jpg', 
//'Suspiria - 1977.mp4','Suspiria - 1977.jpg', 
//'Suspiria - 2018.mkv','Suspiria - 2018.jpg', 
//'Temos Vagas 1 - 2007.mkv','Temos Vagas 1 - 2007.jpg', 
//'Temos Vagas 2 - A Primeira Diária - 2008.mkv','Temos Vagas 2 - A Primeira Diária - 2008.jpg', 
//'Terra Maldita - 2009.mkv','Terra Maldita - 2009.jpg', 
//'Terra dos Mortos - 2005.mkv','Terra dos Mortos - 2005.jpg', 
//'Terras de Sangue - 2014.mkv','Terras de Sangue - 2014.jpg', 
//'Terrifier 1 - 2016.mp4','Terrifier 1 - 2016.jpg', 
//'Terrifier 2 -2022.mkv','Terrifier 2 -2022.jpg', 
//'Terrifier 3.mp4','Terrifier 3.jpg', 
//'Terror em Silent Hill.mkv','Terror em Silent Hill.jpg', 
//'The Birds 1963.mp4','The Birds 1963.jpg', 
//'The Red Book Ritual.mp4','The Red Book Ritual.jpg', 
//'The Sadness 2021.mp4','The Sadness 2021.jpg', 
//'The Silence - 2019.mkv','The Silence - 2019.jpg', 
//'The Woman.mp4','The Woman.jpg', 
//'Tomates Assasinos 2.mkv','Tomates Assasinos 2.jpg', 
//'Tony.mp4','Tony.jpg', 
//'Toque de Recolher - 2006.mkv','Toque de Recolher - 2006.jpg', 
//'Trancada 2022.mkv','Trancada 2022.jpg', 
//'Trem Fantasma - 2006.mkv','Trem Fantasma - 2006.jpg', 
//'Triângulo do Medo - 2009.mkv','Triângulo do Medo - 2009.jpg', 
//'Tubarao 1.mkv','Tubarao 1.jpg', 
//'Tubarao 2.mkv','Tubarao 2.jpg', 
//'Tubarao 3.mkv','Tubarao 3.jpg', 
//'Tubarao 4 - O Ultimo Tubarao.mkv','Tubarao 4 - O Ultimo Tubarao.jpg', 
//'Tubarao 4.mkv','Tubarao 4.jpg', 
//'Turistas - 2006.mkv','Turistas - 2006.jpg', 
//'Tusk A Transformacao.mp4','Tusk A Transformacao.jpg', 
//'Ultimo Mundo Canibal - Faces da Morte 8.mkv','Ultimo Mundo Canibal - Faces da Morte 8.jpg', 
//'Um Clássico Filme de Terror - 2021.mkv','Um Clássico Filme de Terror - 2021.jpg', 
//'Um Drink no Inferno 1 - 1996.mkv','Um Drink no Inferno 1 - 1996.jpg', 
//'Um Drink no Inferno 2 - 1999.mkv','Um Drink no Inferno 2 - 1999.jpg', 
//'Um Drink no Inferno 3 - 2000.mkv','Um Drink no Inferno 3 - 2000.jpg', 
//'Um Lugar Silencioso.mkv','Um Lugar Silencioso.jpg', 
//'Uma Noite Para Esquecer - 2013.mkv','Uma Noite Para Esquecer - 2013.jpg', 
//'Uma Noite de Crime 1 - 2013.mkv','Uma Noite de Crime 1 - 2013.jpg', 
//'Uma Noite de Crime 2 - Anarquia - 2014.mkv','Uma Noite de Crime 2 - Anarquia - 2014.jpg', 
//'Uma Noite de Crime 3 - 2016.mkv','Uma Noite de Crime 3 - 2016.jpg', 
//'Uma Noite de Crime 4 A Primeira Noite de Crime.mp4','Uma Noite de Crime 4 A Primeira Noite de Crime.jpg', 
//'Uma Noite de Crime 5 A Fronteira.mkv','Uma Noite de Crime 5 A Fronteira.jpg', 
//'Vertigo 1958.mp4','Vertigo 1958.jpg', 
//'Verónica - 2017.mkv','Verónica - 2017.jpg', 
//'Viagem Maldita 1 - 2006.mkv','Viagem Maldita 1 - 2006.jpg', 
//'Viagem Maldita 2 - 2007.mkv','Viagem Maldita 2 - 2007.jpg', 
//'Viagem do Medo - 2010.mkv','Viagem do Medo - 2010.jpg', 
//'Vigiados.mp4','Vigiados.jpg', 
//'Você Nunca Me Encontrará (2023).mp4','Você Nunca Me Encontrará (2023).jpg', 
//'Você é o Próximo - 2014.mkv','Você é o Próximo - 2014.jpg', 
//'When Evil Lurks.mp4','When Evil Lurks.jpg', 
//'Wolf Creek 1.mkv','Wolf Creek 1.jpg', 
//'Wolf Creek 2 - 2013 - Legendado.mkv','Wolf Creek 2 - 2013 - Legendado.jpg', 
//'X - A Marca da Morte.mp4','X - A Marca da Morte.jpg', 
//'Ze do caixao - Encarnação Do Demonio.mkv','Ze do caixao - Encarnação Do Demonio.jpg', 
//'Ze do caixao - Esta Noite Encarnarei no Teu Cadáver.mkv','Ze do caixao - Esta Noite Encarnarei no Teu Cadáver.jpg', 
//'Ze do caixao - À Meia Noite Levarei Sua Alma.mkv','Ze do caixao - À Meia Noite Levarei Sua Alma.jpg', 
//'Zoombies 1 - 2016.mkv','Zoombies 1 - 2016.jpg', 
//'Zoombies 2 - 2019.mkv','Zoombies 2 - 2019.jpg', 
//'o Apostolo.mp4','o Apostolo.jpg', 
//'Á Prova de Morte - 2007.mkv','Á Prova de Morte - 2007.jpg', 
//
////novos
//'Carrie, a Estranha - 2002.mp4','Carrie, a Estranha - 2002.jpg', 
]
